### PR TITLE
Fixes #619

### LINKED ISSUE #619: 5.0.0-beta.0 header: true, worker: false, steps... incorrectly parses headers
Here is a failing test:
```
AssertionError: expected '[[{"O":"A"},{"O":"b"},{"O":"c"}],[{"O":"d"},{"O":"E"},{"O":"f"}]]' to deeply equal '[{"One":"A","Two":"b","Three":"c"},{"One":"d","Two":"E","Three":"f"}]'
      + expected - actual

      -[[{"O":"A"},{"O":"b"},{"O":"c"}],[{"O":"d"},{"O":"E"},{"O":"f"}]]
      +[{"One":"A","Two":"b","Three":"c"},{"One":"d","Two":"E","Three":"f"}]
```
<details>
<summary>code</summary>

```js
	{
		description: "Data is correctly parsed with steps (headers)",
		expected: [{One: 'A', Two: 'b', Three: 'c'}, {One: 'd', Two: 'E', Three: 'f'}],
		run: function(callback) {
			var data = [];
			Papa.parse('One,Two,Three\nA,b,c\nd,E,f', {
				header: true,
				step: function(results) {
					data.push(results.data);
				},
				complete: function() {
					callback(data);
				}
			});
		}
	},
	{
		// The worker code path does work,
		// This fails because node doesn't expose Workers yet ... so this falls back to the non-worker path.
		// See: https://nodejs.org/api/worker_threads.html
		description: "Data is correctly parsed with steps and worker (headers)",
		expected: [{One: 'A', Two: 'b', Three: 'c'}, {One: 'd', Two: 'E', Three: 'f'}],
		run: function(callback) {
			var data = [];
			Papa.parse('One,Two,Three\nA,b,c\nd,E,f', {
				header: true,
				worker: true,
				step: function(results) {
					data.push(results.data);
				},
				complete: function() {
					callback(data);
				}
			});
		}
	},
```

</details>

### PR DESCRIPTION
**Pull request by jsg2021**
Adds tests and fixes an issue that incorrectly parses the headers with step functions

### CODE REVIEW

File: papaparse.js [hunk 1]
```diff
@@ -1111,32 +1110,38 @@ License: MIT
...
+				if (isFunction(_config.transformHeader))
+					header = _config.transformHeader(header);
 
-					_fields.push(header);
-				}
-			_results.data.splice(0, 1);
+				_fields.push(header);
+			}
+
+			if (isStep)
```
Comment (pokoli) [inline papaparse.js]: can we test that _config.step is set instead of passing the isStep variable everywhere?

File: papaparse.js [hunk 2]
```diff
@@ -1165,20 +1170,19 @@ License: MIT
...
 			{
 				var row = _config.header ? {} : [];
 
-				var j;
-				for (j = 0; j < _results.data[i].length; j++)
+				function processField(value, j)
 				{
 					var field = j;
-					var value = _results.data[i][j];
+					// var value = _results.data[i][j];
```
Comment (pokoli) [inline papaparse.js]: Why comenting?

File: papaparse.js [hunk 3]
```diff
@@ -1165,20 +1170,19 @@ License: MIT
...
 		}
 
-		function applyHeaderAndDynamicTypingAndTransformation()
+		function applyHeaderAndDynamicTypingAndTransformation(isStep)
 		{
 			if (!_results || (!_config.header && !_config.dynamicTyping && !_config.transform))
 				return _results;
 
-			for (var i = 0; i < _results.data.length; i++)
+			function processRow(rowSource, i)
```
Comment (pokoli) [inline papaparse.js]: Could you avoid refactoring the code into function instead of fors?

I do not say i don't like it but i like to keep commits simple and related to the issue. 

Please open a new PR for this kind of refactoring.

File: papaparse.js [hunk 4]
```diff
@@ -1165,20 +1170,19 @@ License: MIT
...
 			{
 				var row = _config.header ? {} : [];
 
-				var j;
-				for (j = 0; j < _results.data[i].length; j++)
+				function processField(value, j)
```
Comment (pokoli) [inline papaparse.js]: idem about refactoring

File: tests/test-cases.js [hunk 5]
```diff
@@ -1804,6 +1804,42 @@ var CUSTOM_TESTS = [
...
+					data.push(results.data);
+				},
+				complete: function() {
+					callback(data);
+				}
+			});
+		}
+	},
+	{
+		// The worker code path does work,
```
Comment (pokoli) [inline tests/test-cases.js]: I do not understand what is this comment talking about. 

The tests are executed under mocha-chorme and I see this [is psasing on travis.](https://travis-ci.org/mholt/PapaParse/jobs/484479176#L901)

Comment (jsg2021) [reply tests/test-cases.js]: That comment was made while the test was failing... and I didn't realize there was a chrome headless test ...i will remove it.

File: papaparse.js (hunk 3 above)
Comment (jsg2021) [reply papaparse.js]: I was not intending to refactor for refactors sake. If the loop body is not put into a function, it will need to be repeated. I attempted to make the change as minimal as possible.

File: papaparse.js (hunk 4 above)
Comment (jsg2021) [reply papaparse.js]: again, this wasn't a refactor as much as it was reusing the loop body

File: papaparse.js (hunk 2 above)
Comment (jsg2021) [reply papaparse.js]: sorry, that was sloppy. I meant to remove it.

File: papaparse.js (hunk 1 above)
Comment (jsg2021) [reply papaparse.js]: will do.

Comment (jsg2021) [reply papaparse.js]: Okay. this is a problem. `_config.step` is truthy even when you are processing outside of a step...  the problem we are attempting to fix is that the step function calls on the process/parse functions that assume the shape of results is a two dimensional array, when for steps, it's just a single dimension.  We need to tell the those functions the context is one row. not a chunk of rows... Alternatively we could ensure steps use a two dimensional array as well, but limit the length to 1 row... but that is way more invasive at the moment.

Comment (pokoli) [reply papaparse.js]: Then probably is better to make those functions always work with a one dimensional array.

Comment (jsg2021) [reply papaparse.js]: So, are you suggesting to test the shape of `_results.data` instead of passing in the flag?

Comment (jsg2021) [reply papaparse.js]: done. :)

**Comment by jsg2021** [comment]
I think I've addressed your requests? If not let me know :)
